let Coin = require('./coin');
let List = require('./clasGlobal');

module.exports.ListBot = new List({
    InitialDeposit: 2000.0,
    PurseBot: 0.0,
    PriseRate: 120.0000,
    PurseFiatBot: 2000.0,
    PurseCoinBot: 0.0,
    TradingСouple: Coin.ETHRUBCoin.TradingСouple,
    CourseNumberSigns: Coin.ETHRUBCoin.CourseNumberSigns,
    FiatNumberSigns: Coin.ETHRUBCoin.FiatNumberSigns,
    CoinNumberSigns: Coin.ETHRUBCoin.CoinNumberSigns,
    RateLand: Coin.ETHRUBCoin.RateLandSigns,
    RateFall: Coin.ETHRUBCoin.RateFallSigns,
    markerBuy: 0,
    markerSell: 0,
    markerFall: 0,
    markerStopLossBot: 0,
    PurchasePrice: undefined,
    LandSales: undefined,
    FallData: undefined,
    Profit: 0.0,
    ProfitFiat: 0.0,
    VectorBot: 'Buy',
});

// module.exports.ListBot = new List({
//     InitialDeposit: 500.0000,
//     PurseBot: 49.99698,
//     PriseRate: 50.0000,
//     PurseFiatBot: 450.00302,
//     PurseCoinBot: 17.1,
//     TradingСouple: Coin.CTKCoin.TradingСouple,
//     CourseNumberSigns: Coin.CTKCoin.CourseNumberSigns,
//     FiatNumberSigns: Coin.CTKCoin.FiatNumberSigns,
//     CoinNumberSigns: Coin.CTKCoin.CoinNumberSigns,
//     RateLand: Coin.CTKCoin.RateLandSigns,
//     RateFall: Coin.CTKCoin.RateFallSigns,
//     markerBuy: 1,
//     markerSell: 0,
//     markerFall: 0,
//     markerStopLossBot: 0,
//     PurchasePrice: 2.9238,
//     LandSales: 2.9238,
//     FallData: 2.9238,
//     Profit: 0.00,
//     ProfitFiat: 0.00,
//     VectorBot: 'Sell',
// });
